### Constants
@host = 192.168.1.38
@port = 8111
@user = admin
@password = admin

### Hardcoded Data
@projectId = valentina123
@buildTypeId = buildType1

### Generated test data
@projectId1 = {{$random.alphabetic(10)}}
@buildTypeId1 = {{$random.alphabetic(10)}}

#### GET all projects (look in teamcity API documentation)
#GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
#Content-Type: application/json
#Accept: application/json

#### STEPS for creating a build configuration: Step 1: create project. if 403 - comment previous calls to not have previos cookies.

#POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
#Content-Type: application/json
#Accept: application/json
#
#{
#  "parentProject": {
#    "locator": "_Root"
#  },
#  "name": "valentina",
#  "id": "{{projectId}}",
#  "copyAllAssociatedSettings": true
#}
#
#### Step 2: create build type
#POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildTypes
#Content-Type: application/json
#Accept: application/json
#
#{
#  "id": "{{buildTypeId}}",
#  "name": "My Build com.example.teamcity.api.config.Config",
#  "project": {
#    "id": "{{projectId}}"
#  },
#  "steps": {
#    "step": [
#      {
#        "name": "My Step",
#        "type": "simpleRunner",
#        "properties": {
#          "property": [
#            {
#              "name": "use.custom.script",
#              "value": "true"
#            },
#            {
#              "name": "script.content",
#              "value": "echo Hello World!"
#            }
#          ]
#        }
#      }
#    ]
#  }
#}


### Step 3: run build
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
  "buildType": {
    "id": "{{buildTypeId}}"
  }
}
