# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

jobs:
  validate-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Validate Checkstyle
        run: ./mvnw validate

  run-tests:
    needs: validate-checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: TeamCity Setup
        uses: ./.github/actions/teamcity-setup # TeamCity Setup включает установку Java
        # Это локальный composite action
        # не создаёт новую машину
        #
        #выполняется внутри job

      - name: Run tests
        continue-on-error: true
        # указываем группу, чтобы не запустить тесты, связанные с сетапом TeamCity
        run: ./mvnw test -Dtest='com.example.teamcity.${{ inputs.package }}.**' -Dgroups=Regression





