name: Deploy to production

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend to production
        run: echo Происходит деплой бекенда


  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to prod
        run: echo Происходит сам деплой фронта
